/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.busreservation.busresevationsystem;

import java.awt.Frame;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Chirag
 */
public class BookingDialog extends javax.swing.JDialog {

    /**
     * Creates new form BookingDialog
     */
    private String busNo;
    private int seat;
    private double price;
    private String source;
    private String destination;
    private String time;
    private String date;

    public BookingDialog(java.awt.Frame parent, boolean modal, String busNo, String source, String destination, double price, int seat, String time, String date) {
        super(parent, modal);
        initComponents(); // NetBeans-generated method
        setLocationRelativeTo(parent); // Center the dialog

        this.busNo = busNo;
        this.seat = seat;
        this.price = price;
        this.source= source;
        this.destination = destination;
        this.time = time;
        this.date = date;

 
        // Set default values (optional)
        payButton.setText("Confirm & Pay ₹" + price);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        paymentComboBox = new javax.swing.JComboBox<>();
        payButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Booking Form ");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel3.setText("Phone Number");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel4.setText("Email");

        nameField.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        emailField.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        phoneField.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel5.setText("payment Method");

        paymentComboBox.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        paymentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "QR" }));

        payButton.setBackground(new java.awt.Color(51, 204, 0));
        payButton.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        payButton.setText("Confirm & Pay");
        payButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paymentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(payButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameField))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        // TODO add your handling code here:
        String name = nameField.getText().trim();
        String phone = phoneField.getText().trim();
        String email = emailField.getText().trim();
        String paymentMethod = paymentComboBox.getSelectedItem().toString();
        
        if(name.isEmpty() || phone.isEmpty()||email.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill all details!","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm  = JOptionPane.showConfirmDialog(this, "Proceed with Payment?","Payment",JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
            updateSeatAndConfirm();
        }
    }//GEN-LAST:event_payButtonActionPerformed
private void updateSeatAndConfirm() {
    String userName = nameField.getText().trim();
    String contact = phoneField.getText().trim();
    // Validate user inputs
    if (userName.isEmpty() || contact.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter your name and contact number!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try (Connection conn = DatabaseConnection.getConnection()) {
        // Step 1: Update Seat Count
        String updateQuery = "UPDATE bus_details SET seat = seat - 1 WHERE bus_no = ?";
        PreparedStatement stmt = conn.prepareStatement(updateQuery);
        stmt.setString(1, busNo);
        int rows = stmt.executeUpdate();

        if (rows > 0) {
            // Step 2: Insert Booking Details into `bookings` Table
            String insertQuery = "INSERT INTO bookings (user_name, contact, bus_no, source, destination, price, seat_no, time, date, payment_status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

            PreparedStatement insertStmt = conn.prepareStatement(insertQuery);
            insertStmt.setString(1, userName);
            insertStmt.setString(2, contact);
            insertStmt.setString(3, busNo);
            insertStmt.setString(4, source);
            insertStmt.setString(5, destination);
            insertStmt.setDouble(6, price);
            insertStmt.setInt(7, seat);
            insertStmt.setString(8, time);
            insertStmt.setString(9, date);
            insertStmt.setString(10, "Paid");  // Assume payment is successful

            insertStmt.executeUpdate();

            JOptionPane.showMessageDialog(this, 
                "Booking Successful!\nBus NO: " + busNo, 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE
            );

            // Refresh Dashboard Table
            
            dispose(); // Close the dialog
        } else {
            JOptionPane.showMessageDialog(this, 
                "Error updating seat count!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE
            );
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Database Error: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE
        );
    }
}

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(BookingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Define variables inside the method (avoid static reference issues)
            String busNo = "B123"; // Example value
            String source = "City A";
            String destination = "City B";
            double price = 500.0;
            int seat = 10;
            String time = "10:30 AM";
            String date = "2025-04-02";

            // Create and show the dialog
            BookingDialog dialog = new BookingDialog(new javax.swing.JFrame(), true, busNo, source, destination, price, seat, time, date);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton payButton;
    private javax.swing.JComboBox<String> paymentComboBox;
    private javax.swing.JTextField phoneField;
    // End of variables declaration//GEN-END:variables
}
